export const duelingAchievements = [
  { title: "Dueling Club Beginner", requirement: "Reach Bronze Tier in the Dueling Club" },
  { title: "Dueling Club Enthusiast", requirement: "Reach Silver Tier in the Dueling Club" },
  { title: "Dueling Club Connoisseur", requirement: "Reach Gold Tier in the Dueling Club" },
  { title: "Dueling Club Expert", requirement: "Reach Platinum Tier in the Dueling Club" },
  { title: "Dueling Club Champion", requirement: "Reach Diamond Tier in the Dueling Club" },
  { title: "Dueling Club Master", requirement: "Reach Grand Master Tier in the Dueling Club" },
  { title: "Dueling Club Grand Master", requirement: "Reach Magic Awakened Tier in the Dueling Club" },
  { title: "Hot Streak", requirement: "Win 3 Duels of the same category" },
  { title: "Incendiary Streak", requirement: "Win 10 Duels of the same category" },
  { title: "Impossible Streak", requirement: "Win 20 Duels of the same category" },
  { title: "Ninety Second Best", requirement: "Win a Duel at Gold Tier or above within 90 seconds 5 times" },
  { title: "Two For One", requirement: "Defeat two opponents at the same time with a single card in Best Partners 5 times" },
  { title: "Eight’s a Crowd", requirement: "Win with 8 or more of our Summons on the field at Gold Tier or above 5 times" },
  { title: "Pardon The Interruption", requirement: "Use Expelliarmus to interrupt a casting opponent 5 times" },
  { title: "Quick Draw", requirement: "Defeat 2 opponents with rescue attempts left within 2 seconds in Best Partners 5 times" },
  { title: "Dueling Enthusiast", requirement: "Win a total of 5 Duels in the Dueling club" },
  { title: "Dueling Connoisseur", requirement: "Win a total of 10 Duels in the Dueling club" },
  { title: "Dueling Expert", requirement: "Win a total of 50 Duels in the Dueling club" },
  { title: "Dueling Master", requirement: "Win a total of 100 Duels in the Dueling club" },
  { title: "Consummate Survivor", requirement: "Win a duel with less than 10% Health remaining 5 times" },
  { title: "Team Player 1", requirement: "Rescue a teammate in dueling 10 times" },
  { title: "Team Player 2", requirement: "Rescue a teammate in dueling 20 times" },
  { title: "Team Player 3", requirement: "Rescue a teammate in dueling 50 times" },
  { title: "Right Frame of Mind 1", requirement: "Collect a total of 18 MA Duelist portrait frames" },
  { title: "Right Frame of Mind 2", requirement: "Collect a total of 36 MA Duelist portrait frames" },
  { title: "Double Trouble", requirement: "Deal 70% or more damage in a Duel and with at Gold Tier or above 5 times" },
  { title: "Right Back At You", requirement: "Defeat an opponent by changing the direction of an incoming Spell with Apparition 5 times" }
];
