import DADA from '../../../public/assets/Class/DADA.jpg';
import Divination from '../../../public/assets/Class/Divination.jpg';
import MuggleStudies from '../../../public/assets/Class/DADA.jpg';

export const hogwartsClasses = [
  {
    id: 'charms',
    name: 'Charms',
    professor: 'Filius Flitwick',
    description:
      "Charms is a combat track where you'll face a troll in the bathroom. You'll use Wingardium Leviosa to keep the troll's club at bay while reducing its health. Perfecting the spellcasting is required to progress in the class.",
    explanation: 'test',
    src: DADA,
  },
  {
    id: 'careOfMagicalCreatures',
    name: 'Care of Magical Creatures',
    professor: 'Rubeus Hagrid',
    description:
      'Care of Magical Creatures offers two courses: Gnomes and Hippogriffs. In Gnomes class, you defend pumpkins from gnome incursion. In Hippogriff class, you interact with a Hippogriff while battling smaller Hippogriffs.',
    explanation: 'test',
    src: DADA,
  },
  {
    id: 'divination',
    name: 'Divination',
    professor: 'Sybill Trelawney',
    description:
      'Divination involves drawing and guessing what you see in a crystal ball. You will need to get likes from other players to pass the class.',
    explanation: 'test',
    src: Divination,
  },
  {
    id: 'defenseAgainstDarkArts',
    name: 'Defense Against the Dark Arts',
    professor: 'Brindlemore',
    description:
      'Defense Against the Dark Arts offers Boggart and Pixie classes. In Boggart class, you face a shape-shifting Boggart. In Pixie class, you capture pixies using spells. Perfecting the skills is necessary to excel.',
    explanation: 'test',
    src: DADA,
  },
  {
    id: 'studyOfAncientRunes',
    name: 'Study of Ancient Runes',
    professor: 'Clodagh Dromgoole',
    description:
      'Study of Ancient Runes involves a memory match game with runes. You will compete against the Frey twins and aim to match the runes correctly.',
    explanation: 'test',
    src: DADA,
  },
  {
    id: 'muggleStudies',
    name: 'Muggle Studies',
    professor: 'Concordia Rowle',
    description:
      'Muggle Studies is focused on the lives of Muggles. It features an exam format with questions about Muggle technology, lives, and regulations concerning Wizard and Muggle interactions.',
    explanation: 'test',
    src: MuggleStudies,
  },
  {
    id: 'historyOfMagic',
    name: 'History of Magic',
    professor: 'Jakub Gorski',
    description:
      'History of Magic is a test-based class with questions related to the Potterverse. There are two levels of difficulty, and you compete with two other players to answer the questions correctly.',
    explanation: 'test',
    src: DADA,
  },
];

export const historyOfMagicQuestions = [
  { question: "What kind of core did Harry's first wand possess?", answer: "Phoenix Feather" },
  { question: "In 1997, what was written on the statue at the Ministry of Magic under Voldemort’s control?", answer: "Magic is Might" },
  { question: "How did Harry first arrive (and ultimately depart from) the Dursley's house on 4 Privet Drive?", answer: "Sirius Black's Motorcycle" },
  { question: "Who of the following was not a classmate of Harry Potter?", answer: "Fleur Delacour" },
  { question: "What was Gilderoy Lockhart's best spell?", answer: "Obliviate" },
  { question: "What did Professor Snape tell Harry could Detoxify people from most kinds of poisons?", answer: "Bezoar" },
  { question: "What kind of pest repellent was Hagrid looking for when he saw Harry in Knockturn Alley?", answer: "Flesh-eating Slugs" },
  { question: "Who is known as the 'Chosen One'?", answer: "Harry Potter" },
  { question: "Who left the lightning-shaped scar on Harry Potter's forehead?", answer: "Voldemort" },
  { question: "What is used to track House Points for the Hogwarts House Cup?", answer: "Hourglasses with gems" },
  { question: "Who put an end to Nagini?", answer: "Neville Longbottom" },
  { question: "Which dark magic item is known as the friend of thieves?", answer: "The Hand of Glory" },
  { question: "What form does the Weasley Twins’ Patronus take?", answer: "Magpie" },
  { question: "Who is the Half-Blood Prince?", answer: "Severus Snape" },
  { question: "What was Harry Potter's middle name?", answer: "James" },
  { question: "Who was Dobby’s original owner?", answer: "Lucius Malfoy" },
  { question: "Which creatures feed on the human brain and helped Newt Scamander escape?", answer: "Swooping Evil" },
  { question: "Who destroyed the final Horcrux?", answer: "Neville Longbottom" },
  { question: "Which subject does Professor McGonagall teach?", answer: "Transfiguration" },
  { question: "What creature sat in the corner of Professor Lupin's office the first time Harry Potter visited him at Hogwarts?", answer: "Grindylow" },
  { question: "Whose blood did Voldemort drink to stay alive?", answer: "Unicorn's Blood" },
  { question: "Which Ghost haunts the Girls' Bathroom at Hogwarts?", answer: "Moaning Myrtle Warren" },
  { question: "What curse is Harry Potter the only known survivor of?", answer: "Avada Kedavra" },
  { question: "Where did Dumbledore and Grindelwald make the Blood Pact?", answer: "A Barn" },
  { question: "How many siblings does Ron Weasley have?", answer: "Six" },
  { question: "What book did Hermione lend Harry before his first Quidditch match?", answer: "Quidditch Through the Ages" },
  { question: "Where was Harry born?", answer: "Godric's Hollow" },
  { question: "Who killed Sirius Black?", answer: "Bellatrix Lestrange" },
  { question: "What was the name of the house where the Weasleys once lived, which became a second home to Harry Potter?", answer: "The Burrow" },
  { question: "What mode of transportation did Hagrid use to take infant Harry Potter to his aunt and uncle's house at 4 Privet Drive?", answer: "Flying Motorbike" },
  { question: "How long is Harry Potter's wand?", answer: "11 inches" },
  { question: "Where did Harry Potter live with his Muggle relatives, the Dursleys?", answer: "Privet Drive" },
  { question: "Who was Harry Potter's godfather?", answer: "Sirius Black" }
];

export const muggleStudiesQuestions = [
  { question: "Who or what is a plunger?", answer: "A device used to clear pipes" },
  { question: "Why do Muggles wear safety goggles?", answer: "To protect their eyes from foreign objects or debris" },
  { question: "The Hogwarts Express departs from Platform 9 3/4 in which Muggle train station?", answer: "King’s Cross Station" },
  { question: "If a Muggle wanted to get in contact with someone, how might they do it?", answer: "Call them on a phone" },
  { question: "What is a lighter?", answer: "A portable flame generator" },
  { question: "Which of the following is NOT a feature of Muggle chewing gum?", answer: "Never loses its flavour" },
  { question: "Which of the following did NOT occur after the International Statute of Wizarding Secrecy was signed?", answer: "Muggles ramped up their witch hunts" },
  { question: "Which of the following is magnetic?", answer: "A Bludger" },
  { question: "Muggles have grading scales for pencils. What are 2B pencils like compared to 4B pencils?", answer: "Harder" },
  { question: "Which of the following Fantastic Beasts would be most likely to be classified as cold-blooded in Muggle biology?", answer: "Ashwinder" },
  { question: "What is a pogo stick used for?", answer: "Jumping up and down" },
  { question: "Which of the following do Muggles use to listen to music?", answer: "Earbuds" },
  { question: "What is the most popular Muggle sport in the United Kingdom?", answer: "Football" },
  { question: "Who or what is a lawnmower?", answer: "A machine that cuts grass" },
  { question: "Which of the following is NOT a Muggle instrument?", answer: "Dissimulator" },
  { question: "What is a drain snake?", answer: "A tool used to dislodge plumbing clogs" },
  { question: "What do Muggles use cocktail umbrellas for?", answer: "Garnishing drinks" },
  { question: "When Muggles look at Hogwarts, what do they see?", answer: "A mouldering old ruin with a danger sign" },
  { question: "Whose experiments with lightning, a kite, and a metal key led to a greater understanding of electricity?", answer: "Benjamin Franklin" },
  { question: "Which of the following do Muggles use to breathe underwater?", answer: "A snorkel" },
  { question: "What do Muggles mean when they say ‘an apple a day keeps the doctor away’?", answer: "Nutritious foods keep you healthy" },
  { question: "What is the major exception to the Wizarding community’s general aversion to Muggle technology?", answer: "Cars" },
  { question: "Which of the following is NOT something Muggles use the internet for?", answer: "Catching mice" },
  { question: "When was the first mobile phone debuted?", answer: "1973" },
  { question: "What is a disco ball?", answer: "A rotating ball covered with tiny mirrors" },
  { question: "Which of the following is NOT a way Muggles receive news?", answer: "Owl" },
  { question: "Which of the following is NOT a Muggle music storage device?", answer: "Mixer" },
  { question: "Music is a favourite of Muggles. Which city is known as the “music capital” of the world?", answer: "Vienna" },
  { question: "What might a cowboy use as transportation?", answer: "A horse" },
  { question: "What substance cannot conduct electricity?", answer: "Rubber" },
  { question: "Which of the following would be an inappropriate interaction between a Wizard and a Muggle?", answer: "A Wizard sells a Muggle a Shrinking Key" },
  { question: "Which charm do Obliviators use on Muggles who witness magical phenomena?", answer: "Memory Charm" },
  { question: "Which of the following is NOT a form of Muggle trading card?", answer: "Chocolate Frog Cards" },
  { question: "A jet ski transports a Muggle across what?", answer: "Water" },
  { question: "If you wish to enter a Muggle home, what should you do?", answer: "Enter their front door after knocking" },
  { question: "How do microwaves heat food?", answer: "Electromagnetic waves" },
  { question: "Who or what is a plumber?", answer: "A Muggle who installs or repairs pipes" },
  { question: "Which of the following is not one of the famous Muggle author Victor Hugo’s works?", answer: "The Count of Monte Cristo" },
  { question: "What is a car park?", answer: "A place for storing automobiles" },
  { question: "Playgrounds may feature all but which of the following?", answer: "Alligator pit" },
  { question: "What do Muggles use jack-in-the-boxes for?", answer: "Amusement" },
  { question: "Which magical author posited on Muggle tendency to dismiss magic in their book, The Philosophy of the Mundane: Why the Muggles Prefer Not to Know?", answer: "Professor Mordicus Egg" },
  { question: "What is a skipping rope?", answer: "A piece of exercise equipment" },
  { question: "Who or what is a calculator?", answer: "A device that performs mathematical calculations" },
  { question: "What do Muggles go to the cinema to do?", answer: "Watch films" },
  { question: "Who or what is an emoji?", answer: "A digital icon used to express an idea or emotion" },
  { question: "Morning Dew is a potion ingredient? How do Muggles believe it is formed?", answer: "Condensation" },
  { question: "Which of the following materials can Muggles use to remove limescale?", answer: "Vinegar" },
  { question: "Who or what goes haywire at Hogwarts, due to there being too much magic in the air?", answer: "Electronics" },
  { question: "Which of the following is NOT a Muggle clothing style?", answer: "Sticky" },
  { question: "If a Muggle’s house caught on fire, who would they call to put it out?", answer: "Firefighters" },
  { question: "What do Muggles mistake Knarls for?", answer: "Hedgehogs" },
  { question: "Muggles are making efforts to use more renewable energy. Which of the following is not a renewable energy source?", answer: "Natural Gas" },
  { question: "What do Muggles call an electronic device that is able to connect, share, and interact with its user and other devices?", answer: "A smart device" },
  { question: "Which of the following would NOT pop out of a Muggle Christmas cracker?", answer: "A live mouse" },
  { question: "In the height of the Witch-hunts, Wizards who chose to fraternise with Muggles were often treated like what?", answer: "Outcasts" },
  { question: "The ratio of a circle’s circumference to its diameter is called pi. What is pi?", answer: "An infinite non-repeating decimal" },
  { question: "The literary masterpiece War and Peace was written by which Muggle literary figure?", answer: "Leo Tolstoy" },
  { question: "What is the tallest Muggle-made building in the world?", answer: "Burj Khalifa" },
  { question: "Who or what is a veterinarian?", answer: "A Muggle who treats sick or injured animals" },
  { question: "Who do Muggles call if they lock themselves out of their car or house?", answer: "Locksmiths" },
  { question: "Which of the following is a work by the Muggle musician Beethoven?", answer: "Moonlight Sonata" },
  { question: "If a Muggle wanted to fasten an object in place, what might they use?", answer: "Paste" },
  { question: "What do Muggles use curling irons on?", answer: "Their hair" },
  { question: "What is a supermarket?", answer: "A store that sells food" },
  { question: "Which of the following is NOT a fixture in Muggle fiction?", answer: "Flobberworm" },
  { question: "Cola is one of the favourite beverages of Muggles. Do you know what is added to cola to make it bubbly?", answer: "Carbon Dioxide" },
  { question: "In Muggle geography, which is the longest river?", answer: "Nile River" }
];
